const products = [
	{
		id: 0,
		name: "Golden Reserve Blend",
		price: 150,
		description: "0",
		instock: 4,
		imgSrc: "img/bestseller/bs1.jpg",
	},
	{
		id: 1,
		name: "Diamond Infused Espresso",
		price: 200,
		description: "1",
		instock: 2,
		imgSrc: "img/bestseller/bs2.jpg",
	},
	{
		id: 2,
		name: "Royal Velvet Roast",
		price: 180,
		description: "2",
		instock: 2,
		imgSrc: "img/bestseller/bs3.jpg",
	},
	{
		id: 3,
		name: "Platinum Perfection Latte",
		price: 160,
		description: "3",
		instock: 3,
		imgSrc: "img/bestseller/bs4.jpg",
	},
	{
		id: 4,
		name: "Emerald Elixir Cappuccino",
		price: 170,
		description: "4",
		instock: 4,
		imgSrc: "img/bestseller/bs5.jpg",
	},
	{
		id: 5,
		name: "Opulent Obsidian Mocha",
		price: 190,
		description: "5",
		instock: 5,
		imgSrc: "img/bestseller/bs6.jpg",
	},
];
